export const COMMAND_QUERY_MAX_CHARS = 80;
export const COMMAND_ANSWER_MAX_CHARS = 280;
export const COMMAND_ERROR_MAX_CHARS = 160;
export const COMMAND_ACTIONS_MAX = 8;

export const COMMAND_RATE_LIMIT_WINDOW_MS = 60_000;
export const COMMAND_RATE_LIMIT_MAX_REQUESTS = 12;
